[package]
name = "beacon-contract-indexer"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy = { version = "1.0.9"}

tokio = { version = "1.42", features = ["rt-multi-thread", "macros", "full", "signal"] }

clap = { version = "4.0", features = ["derive"] }

futures = "0.3"

